server:
  port: 8080
spring:
  application:
    name: "LabDocker"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  region: "us-east-1"
  secretName: "secret-api-connect"
  urlDocker: "http://ip172-18-0-97-cmbc1vio7r5g00bg40vg-4566.direct.labs.play-with-docker.com"
